# Generated by Django 6.1.1 on 2026-10-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_tests', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('test', 'question_number'), name='unique_question_number_per_test'),
        ),
    ]
